"""The three price-recommendation routes over HTTP (R4.5, R5.1-R5.5; design D10, D12, D14).

What only the API can prove, and why each of these is here rather than in
`test_use_cases.py`: the report shape R4.5 promises, the `409` R5.4 promises for an illegal
move (a use-case test sees an exception, not a status), and the fact that no transition
reaches the `PMSAdapter` **through the wired application** — the wiring is where a
collaborator would be smuggled in, not the use case.

Horizons here are generated by the route, so they start relative to *today* rather than to
the fixtures' `TODAY`: `now_utc()` is what the router passes, which is the point of
`auth_header` stamping its token at the wall clock.
"""

import uuid
from datetime import date, timedelta

import pytest

from app.pricing.domain.constants import HORIZON_DAYS
from app.pricing.domain.enums import PriceRecommendationStatus
from tests.pricing.conftest import (  # noqa: F401
    api,
    auth_header,
    make_recommendation,
    make_rule,
    world,
)

pytestmark = pytest.mark.asyncio

RULES = "/api/v1/pricing-rules"
RECOMMENDATIONS = "/api/v1/price-recommendations"


async def _rule(api, world, **overrides) -> str:
    body = {
        "name": "Madrid base",
        "base_price": "100.00",
        "min_price": "50.00",
        "max_price": "200.00",
        "property_id": str(world.property.id),
    }
    body.update(overrides)
    response = await api.post(RULES, json=body, headers=auth_header(api, world.manager))
    assert response.status_code == 201, response.text
    return response.json()["id"]


async def _generate(api, world, **body):
    return await api.post(
        f"{RECOMMENDATIONS}/generate",
        json=body,
        headers=auth_header(api, world.manager),
    )


# --- POST /generate (R4.5, OQ4) -----------------------------------------------------------


async def test_generating_reports_the_four_counters(api, world) -> None:
    """R4.5 — "devolver cuántas recomendaciones creó y cuántas actualizó"."""
    await _rule(api, world)

    response = await _generate(api, world, property_id=str(world.property.id))

    assert response.status_code == 200, response.text
    assert response.json() == {
        "created": HORIZON_DAYS,
        "updated": 0,
        "preserved": 0,
        "skipped": 0,
    }


async def test_the_report_does_not_publish_the_failure_counter(api, world) -> None:
    """D9/D10: `failed` is the sweep's own accounting, reported to the log with the property
    that caused it. The published contract carries the four of R4.5 and no more, so a client
    cannot start depending on a field the design keeps internal."""
    await _rule(api, world)

    response = await _generate(api, world)

    assert set(response.json()) == {"created", "updated", "preserved", "skipped"}


async def test_generating_twice_updates_instead_of_failing(api, world) -> None:
    """R4.2 — idempotent against the `UNIQUE (property_id, date)`, not by a prior read."""
    await _rule(api, world)
    scope = {"property_id": str(world.property.id)}

    first = await _generate(api, world, **scope)
    second = await _generate(api, world, **scope)

    assert first.json()["created"] == HORIZON_DAYS
    assert second.json() == {
        "created": 0,
        "updated": HORIZON_DAYS,
        "preserved": 0,
        "skipped": 0,
    }


async def test_a_property_without_a_rule_is_skipped_not_failed(api, world) -> None:
    """R4.6 — "omitirla sin error y sin dejar el job en fallo". Both properties of the tenant
    are active and neither has a rule, so the sweep finishes green with everything skipped."""
    response = await _generate(api, world)

    assert response.status_code == 200
    assert response.json() == {"created": 0, "updated": 0, "preserved": 0, "skipped": 2}


async def test_omitting_the_property_sweeps_the_whole_tenant(api, world) -> None:
    """OQ4 — the case that motivates the endpoint: a tenant-wide rule just changed."""
    await _rule(api, world, property_id=None)

    response = await _generate(api, world)

    # Two active properties in the fixture world, both covered by the tenant-wide rule.
    assert response.json()["created"] == HORIZON_DAYS * 2
    assert response.json()["skipped"] == 0


async def test_an_approved_recommendation_survives_a_regeneration(api, world) -> None:
    """R4.3 — "una decisión humana no se sobrescribe por una regeneración", end to end."""
    await _rule(api, world)
    await _generate(api, world)
    listing = await api.get(
        RECOMMENDATIONS, params={"per_page": 1}, headers=auth_header(api, world.manager)
    )
    target = listing.json()["items"][0]
    approved = await api.patch(
        f"{RECOMMENDATIONS}/{target['id']}",
        json={"status": PriceRecommendationStatus.APPROVED.value},
        headers=auth_header(api, world.manager),
    )
    assert approved.status_code == 200, approved.text

    again = await _generate(api, world)
    after = await api.get(
        f"{RECOMMENDATIONS}", params={"per_page": 100}, headers=auth_header(api, world.manager)
    )

    assert again.json()["preserved"] == 1
    assert again.json()["updated"] == HORIZON_DAYS - 1
    survivor = next(
        item for item in after.json()["items"] if item["id"] == target["id"]
    )
    assert survivor["status"] == PriceRecommendationStatus.APPROVED.value
    assert survivor["recommended_price"] == target["recommended_price"]


async def test_naming_an_unknown_property_is_a_422(api, world) -> None:
    """D9's fourth refinement: the scope travels in the **body**, so an unknown id there is a
    validation failure — the `404` of R1.7 belongs to the path."""
    response = await _generate(api, world, property_id=str(uuid.uuid4()))

    assert response.status_code == 422, response.text


async def test_naming_another_tenants_property_is_the_same_422(api, world) -> None:
    """R1.7's indistinguishability applied to this body field: "unknown" and "somebody
    else's" share one constant message, so the endpoint is not a portfolio oracle."""
    unknown = await _generate(api, world, property_id=str(uuid.uuid4()))
    theirs = await _generate(api, world, property_id=str(world.other_property.id))

    assert unknown.status_code == theirs.status_code == 422
    assert unknown.json() == theirs.json()


async def test_naming_an_inactive_property_is_a_422_that_says_so(api, world, db_session) -> None:
    """D9's third refinement. "Yours but inactive" is a fact about the caller's **own**
    portfolio, so naming it is not an oracle — and it is the actionable answer, where counting
    it in `skipped` would mix it with R4.6's meaning."""
    from app.properties.domain.enums import PropertyStatus

    world.property.status = PropertyStatus.INACTIVE
    await db_session.flush()

    response = await _generate(api, world, property_id=str(world.property.id))

    assert response.status_code == 422, response.text
    assert "ACTIVE" in response.json()["error"]["message"]


async def test_the_human_route_writes_one_audit_row_per_repriced_property(
    api, world, db_session
) -> None:
    """R4.1/R4.5 through D12 as narrowed on 2026-08-17: rule 9's fifth exception covers the
    clock and only the clock, because "ausencia de actor" is false of this request — it
    carries a user and an IP. Without the row, a manager could reprice repeatedly with no
    trace in **either** sink: a full horizon inserts nothing, so D14 emits no timeline event.
    """
    from sqlalchemy import select

    from app.audit.domain import actions as audit_actions
    from app.audit.infrastructure.models import AuditLogModel

    await _rule(api, world)
    await _generate(api, world, property_id=str(world.property.id))

    rows = (
        await db_session.execute(
            select(AuditLogModel).where(
                AuditLogModel.action == audit_actions.PRICE_RECOMMENDATIONS_GENERATED
            )
        )
    ).scalars().all()

    assert len(rows) == 1
    assert rows[0].entity_type == audit_actions.ENTITY_PROPERTY
    assert rows[0].entity_id == world.property.id
    assert rows[0].actor_user_id == world.manager.id
    # **And the IP**, which is the half that makes rule 9's narrowing meaningful: the fifth
    # exception covers the clock because it has no actor *and no request to take an `actor_ip`
    # from*, and this path has both. Asserting only `actor_user_id` would let a header-parsing
    # regression quietly make the design's own justification false. Raised by the section-6
    # security panel.
    assert rows[0].actor_ip, "the human generate path recorded no actor_ip (rule 9, D12)"
    # No diff: the audited fact is "this person repriced this property", and the counters live
    # in the response and the log rather than in a second place.
    assert rows[0].changes in ({}, None)


async def test_a_decision_writes_its_audit_row_with_the_actor(api, world, db_session) -> None:
    """R5.2 — "aplicar la transición y registrar un `AuditLog` con el actor", over HTTP.

    The transition itself is asserted above; this is the audit half, which no API test covered.
    It matters at this level rather than only in `test_use_cases.py` because the actor is built
    in the **router** (`_actor(...)`), so a refactor there could drop the person while every
    status assertion stayed green — and `_AuditWriter` would then raise rather than write, which
    is a 500 on a path R5.2 promises as a 200. Raised by the section-6 QA panel.
    """
    from sqlalchemy import select

    from app.audit.domain import actions as audit_actions
    from app.audit.infrastructure.models import AuditLogModel

    target = await _one_recommendation(api, world)
    response = await _move(api, world, target["id"], PriceRecommendationStatus.APPROVED)
    assert response.status_code == 200, response.text

    rows = (
        await db_session.execute(
            select(AuditLogModel).where(
                AuditLogModel.action == audit_actions.PRICE_RECOMMENDATION_DECIDED
            )
        )
    ).scalars().all()

    assert len(rows) == 1
    assert rows[0].entity_type == audit_actions.ENTITY_PRICE_RECOMMENDATION
    assert rows[0].entity_id == uuid.UUID(target["id"])
    assert rows[0].actor_user_id == world.manager.id
    assert rows[0].actor_ip
    # `status` is the entity's whole auditable surface (D12), which is what keeps the rendered
    # `explanation` — a censused sink of rule 11 — out of `audit_logs.changes`.
    assert set(rows[0].changes) == {"status"}


async def test_marking_applied_external_writes_its_own_audit_action(
    api, world, db_session
) -> None:
    """D12 — `PRICE_RECOMMENDATION_APPLIED_EXTERNAL` is a separate action, "porque no es una
    decisión sino un hecho del mundo". Two actions, so a review can ask the two questions
    apart; sharing one would put "what was decided" and "what was published" in one bucket."""
    from sqlalchemy import select

    from app.audit.domain import actions as audit_actions
    from app.audit.infrastructure.models import AuditLogModel

    target = await _one_recommendation(api, world)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPROVED)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPLIED_EXTERNAL)

    actions = (
        await db_session.execute(
            select(AuditLogModel.action).where(
                AuditLogModel.entity_id == uuid.UUID(target["id"])
            )
        )
    ).scalars().all()

    assert sorted(actions) == sorted(
        [
            audit_actions.PRICE_RECOMMENDATION_DECIDED,
            audit_actions.PRICE_RECOMMENDATION_APPLIED_EXTERNAL,
        ]
    )


# --- GET /price-recommendations (R5.1) ----------------------------------------------------


async def test_the_listing_is_paginated_and_filtered(api, world) -> None:
    await _rule(api, world, property_id=None)
    await _generate(api, world)
    headers = auth_header(api, world.manager)
    tomorrow = date.today() + timedelta(days=1)

    first_page = await api.get(RECOMMENDATIONS, params={"per_page": 5}, headers=headers)
    by_property = await api.get(
        RECOMMENDATIONS,
        params={"property_id": str(world.property.id), "per_page": 100},
        headers=headers,
    )
    one_day = await api.get(
        RECOMMENDATIONS,
        params={"date_from": tomorrow.isoformat(), "date_to": tomorrow.isoformat()},
        headers=headers,
    )
    recommended = await api.get(
        RECOMMENDATIONS,
        params={"status": PriceRecommendationStatus.APPROVED.value},
        headers=headers,
    )

    assert len(first_page.json()["items"]) == 5
    assert first_page.json()["total"] == HORIZON_DAYS * 2
    assert by_property.json()["total"] == HORIZON_DAYS
    assert one_day.json()["total"] == 2
    assert recommended.json()["total"] == 0


async def test_each_item_carries_its_explanation_and_a_null_current_price(api, world) -> None:
    """R6.1 on the surface it exists for, and R5.5/D19 on the field that stays empty."""
    await _rule(api, world)
    await _generate(api, world)

    response = await api.get(
        RECOMMENDATIONS, params={"per_page": 1}, headers=auth_header(api, world.manager)
    )

    item = response.json()["items"][0]
    assert item["explanation"].startswith("Base price 100.00 EUR.")
    assert "Recommended" in item["explanation"]
    assert item["current_price"] is None
    assert item["confidence"] == "1.00"
    assert "tenant_id" not in item


async def test_the_listing_never_crosses_tenants(api, world, db_session) -> None:
    """DoD §28.18. The neighbour's row is seeded directly: a request as their manager would
    bind the shared session to their tenant and answer the next caller `401`."""
    from app.pricing.infrastructure.repositories import (
        SqlAlchemyPricingRuleRepository,
    )

    theirs = make_rule(world.other_tenant.id, property_id=world.other_property.id)
    await SqlAlchemyPricingRuleRepository(db_session).add(world.other_tenant.id, theirs)
    await db_session.flush()
    db_session.add(
        _model_of(
            make_recommendation(
                world.other_tenant.id, world.other_property.id, theirs.id
            )
        )
    )
    await db_session.flush()

    await _rule(api, world)
    await _generate(api, world, property_id=str(world.property.id))
    response = await api.get(
        RECOMMENDATIONS, params={"per_page": 100}, headers=auth_header(api, world.manager)
    )

    assert response.json()["total"] == HORIZON_DAYS
    assert {item["property_id"] for item in response.json()["items"]} == {
        str(world.property.id)
    }


def _model_of(recommendation):
    from app.pricing.infrastructure.models import PriceRecommendationModel

    return PriceRecommendationModel(
        id=recommendation.id,
        tenant_id=recommendation.tenant_id,
        property_id=recommendation.property_id,
        pricing_rule_id=recommendation.pricing_rule_id,
        date=recommendation.date,
        recommended_price=recommendation.recommended_price,
        explanation=recommendation.explanation,
        confidence=recommendation.confidence,
        status=recommendation.status,
    )


# --- PATCH /price-recommendations/{id} (R5.2-R5.5) ----------------------------------------


async def _one_recommendation(api, world) -> dict:
    await _rule(api, world)
    await _generate(api, world, property_id=str(world.property.id))
    listing = await api.get(
        RECOMMENDATIONS, params={"per_page": 1}, headers=auth_header(api, world.manager)
    )
    return listing.json()["items"][0]


async def _move(api, world, recommendation_id, status: PriceRecommendationStatus):
    return await api.patch(
        f"{RECOMMENDATIONS}/{recommendation_id}",
        json={"status": status.value},
        headers=auth_header(api, world.manager),
    )


@pytest.mark.parametrize(
    "status", [PriceRecommendationStatus.APPROVED, PriceRecommendationStatus.REJECTED]
)
async def test_a_recommendation_can_be_approved_or_rejected(api, world, status) -> None:
    """R5.2 — the two decisions, from `RECOMMENDED`."""
    target = await _one_recommendation(api, world)

    response = await _move(api, world, target["id"], status)

    assert response.status_code == 200, response.text
    assert response.json()["status"] == status.value


async def test_an_approved_recommendation_can_be_marked_applied_externally(
    api, world
) -> None:
    """R5.3 — the record that a human published that price outside the system."""
    target = await _one_recommendation(api, world)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPROVED)

    response = await _move(
        api, world, target["id"], PriceRecommendationStatus.APPLIED_EXTERNAL
    )

    assert response.status_code == 200, response.text
    assert response.json()["status"] == PriceRecommendationStatus.APPLIED_EXTERNAL.value


async def test_marking_applied_external_puts_the_event_on_the_timeline(
    api, world, db_session
) -> None:
    """R5.3/D14 — and it is the only one of the three moves that emits a timeline row."""
    from sqlalchemy import select

    from app.timeline.domain.enums import TimelineActorType, TimelineEventType
    from app.timeline.infrastructure.models import TimelineEventModel

    target = await _one_recommendation(api, world)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPROVED)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPLIED_EXTERNAL)

    rows = (
        await db_session.execute(
            select(TimelineEventModel).where(
                TimelineEventModel.event_type == TimelineEventType.PRICE_UPDATED_EXTERNAL
            )
        )
    ).scalars().all()

    assert len(rows) == 1
    assert rows[0].property_id == world.property.id
    assert rows[0].actor_type == TimelineActorType.USER
    assert rows[0].actor_user_id == world.manager.id
    # Identifiers and a price, and nothing else (D14): the rendered `explanation` is a censused sink
    # of rule 11 and `timeline_events` is append-only, so anything landing here could never
    # be redacted afterwards.
    assert set(rows[0].metadata_) == {"recommendation_id", "date", "recommended_price"}
    assert rows[0].metadata_["recommendation_id"] == target["id"]


@pytest.mark.parametrize(
    "status",
    [
        # Not a decision: `APPLIED_EXTERNAL` from `RECOMMENDED` skips the approval.
        PriceRecommendationStatus.APPLIED_EXTERNAL,
        # Not a decision at all — `DRAFT` is declared by PRD §7.18 and no path produces it.
        PriceRecommendationStatus.DRAFT,
        # Its own current status, which is still not one of the three legal moves.
        PriceRecommendationStatus.RECOMMENDED,
    ],
)
async def test_an_illegal_move_is_a_409_and_leaves_the_status_intact(
    api, world, status
) -> None:
    """R5.4 — "responder `409` y dejar el estado intacto"."""
    target = await _one_recommendation(api, world)

    response = await _move(api, world, target["id"], status)
    after = await api.get(
        f"{RECOMMENDATIONS}", params={"per_page": 100}, headers=auth_header(api, world.manager)
    )

    assert response.status_code == 409, response.text
    assert response.json()["error"]["code"] == "CONFLICT"
    unchanged = next(item for item in after.json()["items"] if item["id"] == target["id"])
    assert unchanged["status"] == PriceRecommendationStatus.RECOMMENDED.value


async def test_a_status_outside_the_enum_is_a_422(api, world) -> None:
    """The schema's job, and a different failure from the `409` above: an unparseable value
    never reaches the state machine, so calling it a conflict would be a lie."""
    target = await _one_recommendation(api, world)

    response = await api.patch(
        f"{RECOMMENDATIONS}/{target['id']}",
        json={"status": "PUBLISHED"},
        headers=auth_header(api, world.manager),
    )

    assert response.status_code == 422


async def test_an_unknown_recommendation_is_a_404(api, world) -> None:
    response = await _move(api, world, uuid.uuid4(), PriceRecommendationStatus.APPROVED)

    assert response.status_code == 404
    assert response.json()["error"]["code"] == "NOT_FOUND"


async def test_the_three_transitions_complete_without_any_pms_wiring(api, world) -> None:
    """R5.5, Mode 1 of PRD §19 — asserted through the **wired** application.

    Task 5.8 already spies the port from a use-case test, and that is the behavioural half.
    This is the half only the API can give: `api/dependencies.py` is where a collaborator gets
    smuggled in, and a use case that constructs itself cannot notice what the wiring handed
    it. So the claim is structural and stronger than a spy — **no module of `app/pricing/`
    imports `app.integrations` at all**, which is what makes "never calls the PMS" impossible
    rather than merely untested.
    """
    import ast
    from pathlib import Path

    import app.pricing as pricing

    target = await _one_recommendation(api, world)
    await _move(api, world, target["id"], PriceRecommendationStatus.APPROVED)
    applied = await _move(
        api, world, target["id"], PriceRecommendationStatus.APPLIED_EXTERNAL
    )
    assert applied.status_code == 200

    # **Over the AST, not over `vars(module)`.** An earlier version walked the imported
    # modules' namespaces, which only sees module-level names: a function-local
    # `from app.integrations.domain.ports import PMSPort` inside a route body never appears
    # there, so the check would have missed exactly the edit it exists to forbid — and its own
    # docstring claimed structural impossibility. Raised by the section-6 QA panel. Parsing the
    # source catches an import at any depth, including inside a function or a `TYPE_CHECKING`
    # block, and needs no module to be imported first.
    package_root = Path(pricing.__path__[0])
    offenders: dict[str, list[str]] = {}
    for source_file in sorted(package_root.glob("**/*.py")):
        tree = ast.parse(source_file.read_text(encoding="utf-8"))
        named: list[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                named += [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module:
                named.append(node.module)
        integrations = [name for name in named if name.split(".")[:2] == ["app", "integrations"]]
        if integrations:
            offenders[str(source_file.relative_to(package_root))] = integrations

    assert offenders == {}


async def test_the_pms_guard_would_notice_a_function_local_import(tmp_path) -> None:
    """The guard on the guard above — a structural check that cannot fail proves nothing.

    The previous version of that walk passed on a module with a function-local import of
    `app.integrations`, which is the one form somebody adding a PMS call in a hurry would write.
    This feeds the same matcher a file containing exactly that and requires it to be caught, so
    the claim "no module of `app/pricing/` imports `app.integrations` at all" stays a claim the
    test can actually refute.
    """
    import ast

    probe = tmp_path / "sneaky.py"
    probe.write_text(
        "def publish():\n"
        "    from app.integrations.domain.ports import PMSPort\n"
        "    return PMSPort\n",
        encoding="utf-8",
    )

    tree = ast.parse(probe.read_text(encoding="utf-8"))
    named: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            named += [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom) and node.module:
            named.append(node.module)

    assert [name for name in named if name.split(".")[:2] == ["app", "integrations"]] == [
        "app.integrations.domain.ports"
    ]


async def test_the_route_writes_the_same_notification_the_nightly_job_does(
    api, world, db_session
) -> None:
    """R4.5 — «tanto en la ejecución del job nocturno (sin actor) como en `POST /generate`».

    Task 6.7 asked for this and it was missing: every other R4 test drives the use case
    directly with no `actor`, so the authenticated path was wired but unverified. The section
    6/7 QA panel named the exact regression that would have gone unnoticed — someone adding
    `if actor is None:` around the notify call, by analogy with the real `if actor is not
    None:` audit branch three lines below it, breaking the human path while every
    `tests/pricing` test stayed green.
    """
    from sqlalchemy import select

    from app.notifications.infrastructure.models import NotificationLogModel

    await _rule(api, world)

    response = await _generate(api, world, property_id=str(world.property.id))
    assert response.status_code == 200, response.text
    assert response.json()["created"] == HORIZON_DAYS

    rows = await db_session.execute(
        select(NotificationLogModel).where(
            NotificationLogModel.tenant_id == world.tenant.id,
            NotificationLogModel.notification_type == "PRICE_RECOMMENDATION",
        )
    )
    written = list(rows.scalars())

    # The same row the job writes: one per recipient (manager + owner), on the property,
    # with no deadline — and emphatically not one per created recommendation.
    assert {row.recipient_user_id for row in written} == {world.manager.id, world.owner.id}
    assert {row.related_id for row in written} == {world.property.id}
    assert all(row.related_type == "property" for row in written)
    assert all(row.sla_deadline_at is None for row in written)
