"""baseline domain foundation core

Revision ID: 4a5faad7796b
Revises: 
Create Date: 2026-07-17 00:46:36.239622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a5faad7796b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Autogenerate creates these Postgres ENUM types implicitly (as a side
# effect of the first CREATE TABLE that references each one) but never
# emits DROP TYPE for them on downgrade — dropped explicitly below to avoid
# leaving orphaned types (R4.2).
_ENUM_TYPE_NAMES = [
    "tenant_status",
    "guest_document_type",
    "guest_document_status",
    "legal_registration_status",
    "property_operational_state",
    "property_status",
    "storage_type",
    "user_role",
    "user_status",
    "state_transition_triggered_by",
    "reservation_channel",
    "reservation_status",
    "payment_status",
    "access_status",
    "timeline_actor_type",
    "timeline_event_type",
    "timeline_severity",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='ES', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Madrid', nullable=False),
    sa.Column('default_language', sa.String(length=5), server_default='es', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenant_status'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), server_default='es', nullable=False),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('document_type', sa.Enum('DNI', 'NIE', 'PASSPORT', 'RESIDENCE_CARD', 'OTHER', name='guest_document_type'), nullable=True),
    sa.Column('document_number_encrypted', sa.String(), nullable=True),
    sa.Column('document_expiry_date', sa.Date(), nullable=True),
    sa.Column('document_status', sa.Enum('NOT_PROVIDED', 'PENDING', 'PROVIDED', 'VERIFIED', 'REJECTED', name='guest_document_status'), server_default='NOT_PROVIDED', nullable=False),
    sa.Column('legal_registration_status', sa.Enum('NOT_REQUIRED', 'PENDING_GUEST_DATA', 'READY_TO_SUBMIT', 'SUBMITTED', 'FAILED', 'MANUAL_REVIEW', name='legal_registration_status'), server_default='NOT_REQUIRED', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_tenant_id'), 'guests', ['tenant_id'], unique=False)
    op.create_index('ix_guests_tenant_id_email', 'guests', ['tenant_id', 'email'], unique=False)
    op.create_table('properties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=False),
    sa.Column('pms_external_id', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), server_default='ES', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Madrid', nullable=False),
    sa.Column('max_guests', sa.Integer(), server_default='2', nullable=False),
    sa.Column('bedrooms', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bathrooms', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_operational_state', sa.Enum('VACANT_READY', 'AWAITING_CHECKIN', 'OCCUPIED_ESTIMATED', 'AWAITING_CLEANING', 'CLEANING_SCHEDULED', 'CLEANING_IN_PROGRESS', 'READY_FOR_NEXT_GUEST', 'MAINTENANCE_REQUIRED', 'CRITICAL_INCIDENT', 'BLOCKED_BY_OWNER', 'OUT_OF_SERVICE', name='property_operational_state'), server_default='VACANT_READY', nullable=False),
    sa.Column('default_check_in_time', sa.Time(), server_default='15:00:00', nullable=False),
    sa.Column('default_check_out_time', sa.Time(), server_default='11:00:00', nullable=False),
    sa.Column('wifi_name', sa.String(length=200), nullable=True),
    sa.Column('wifi_password_encrypted', sa.String(), nullable=True),
    sa.Column('access_notes', sa.String(), nullable=True),
    sa.Column('cleaning_notes', sa.String(), nullable=True),
    sa.Column('emergency_notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='property_status'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_code', name='uq_properties_tenant_id_internal_code')
    )
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_index('ix_properties_tenant_id_current_operational_state', 'properties', ['tenant_id', 'current_operational_state'], unique=False)
    op.create_index('ix_properties_tenant_id_pms_external_id', 'properties', ['tenant_id', 'pms_external_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('owner_approval_threshold_eur', sa.Numeric(precision=10, scale=2), server_default='100.00', nullable=False),
    sa.Column('ai_confidence_threshold', sa.Numeric(precision=3, scale=2), server_default='0.75', nullable=False),
    sa.Column('sla_critical_minutes', sa.Integer(), server_default='5', nullable=False),
    sa.Column('sla_high_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('sla_medium_minutes', sa.Integer(), server_default='240', nullable=False),
    sa.Column('sla_low_minutes', sa.Integer(), server_default='480', nullable=False),
    sa.Column('checkin_window_hours_before', sa.Integer(), server_default='2', nullable=False),
    sa.Column('checkout_ready_hours_after', sa.Integer(), server_default='1', nullable=False),
    sa.Column('auto_create_cleaning_task', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cleaning_photo_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('storage_type', sa.Enum('LOCAL', 'S3', name='storage_type'), server_default='LOCAL', nullable=False),
    sa.Column('notification_email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notification_whatsapp_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_OWNER', 'PROPERTY_MANAGER', 'CLEANER', 'TECHNICIAN', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='user_status'), server_default='ACTIVE', nullable=False),
    sa.Column('preferred_language', sa.String(length=5), server_default='es', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_id_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_id_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_index('ix_users_tenant_id_status', 'users', ['tenant_id', 'status'], unique=False)
    op.create_table('property_state_transitions',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('to_state', sa.Enum('VACANT_READY', 'AWAITING_CHECKIN', 'OCCUPIED_ESTIMATED', 'AWAITING_CLEANING', 'CLEANING_SCHEDULED', 'CLEANING_IN_PROGRESS', 'READY_FOR_NEXT_GUEST', 'MAINTENANCE_REQUIRED', 'CRITICAL_INCIDENT', 'BLOCKED_BY_OWNER', 'OUT_OF_SERVICE', name='property_operational_state'), nullable=False),
    sa.Column('triggered_by', sa.Enum('SYSTEM', 'USER', 'SCHEDULER', 'WEBHOOK', name='state_transition_triggered_by'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('from_state', sa.Enum('VACANT_READY', 'AWAITING_CHECKIN', 'OCCUPIED_ESTIMATED', 'AWAITING_CLEANING', 'CLEANING_SCHEDULED', 'CLEANING_IN_PROGRESS', 'READY_FOR_NEXT_GUEST', 'MAINTENANCE_REQUIRED', 'CRITICAL_INCIDENT', 'BLOCKED_BY_OWNER', 'OUT_OF_SERVICE', name='property_operational_state'), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_state_transitions_property_id_created_at', 'property_state_transitions', ['property_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_property_state_transitions_tenant_id'), 'property_state_transitions', ['tenant_id'], unique=False)
    op.create_table('reservations',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('external_pms_id', sa.String(length=200), nullable=True),
    sa.Column('external_channel_id', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.Enum('AIRBNB', 'BOOKING', 'EXPEDIA', 'DIRECT', 'MANUAL', 'OTHER', name='reservation_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'CHECKED_IN_ESTIMATED', 'CHECKED_OUT_ESTIMATED', 'COMPLETED', 'NO_SHOW', name='reservation_status'), server_default='PENDING', nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), server_default='1', nullable=False),
    sa.Column('children', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_guests', sa.Integer(), server_default='1', nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ota_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'PARTIALLY_PAID', 'REFUNDED', name='payment_status'), server_default='PENDING', nullable=False),
    sa.Column('access_status', sa.Enum('PENDING', 'CREATED_EXTERNAL', 'MANUAL_ADDED', 'DELIVERED', 'EXPIRED', 'NOT_REQUIRED', name='access_status'), server_default='PENDING', nullable=False),
    sa.Column('legal_registration_status', sa.Enum('NOT_REQUIRED', 'PENDING_GUEST_DATA', 'READY_TO_SUBMIT', 'SUBMITTED', 'FAILED', 'MANUAL_REVIEW', name='legal_registration_status'), server_default='NOT_REQUIRED', nullable=False),
    sa.Column('cleaning_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('special_requests', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_pms_id', name='uq_reservations_tenant_id_external_pms_id')
    )
    op.create_index('ix_reservations_property_id_check_in_date', 'reservations', ['property_id', 'check_in_date'], unique=False)
    op.create_index('ix_reservations_property_id_check_out_date', 'reservations', ['property_id', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_tenant_id'), 'reservations', ['tenant_id'], unique=False)
    op.create_index('ix_reservations_tenant_id_status', 'reservations', ['tenant_id', 'status'], unique=False)
    op.create_table('timeline_events',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'USER', 'GUEST', 'SCHEDULER', 'WEBHOOK', 'AI', name='timeline_actor_type'), nullable=False),
    sa.Column('event_type', sa.Enum('RESERVATION_IMPORTED', 'RESERVATION_CREATED_MANUAL', 'RESERVATION_UPDATED', 'RESERVATION_CANCELLED', 'CHECKIN_WINDOW_OPENED', 'CHECKOUT_WINDOW_REACHED', 'PROPERTY_STATE_CHANGED', 'ACCESS_CODE_PENDING', 'ACCESS_CODE_CREATED_EXTERNAL', 'ACCESS_CODE_MANUAL_ADDED', 'ACCESS_CODE_DELIVERED', 'GUEST_MESSAGE_RECEIVED', 'AI_RESPONSE_SENT', 'AI_ESCALATED_TO_HUMAN', 'HUMAN_RESPONSE_SENT', 'CLEANING_TASK_CREATED', 'CLEANER_ASSIGNED', 'CLEANER_ACCEPTED', 'CLEANER_REJECTED', 'CLEANING_STARTED', 'CLEANING_PHOTO_UPLOADED', 'CLEANING_COMPLETED', 'CLEANING_FAILED_VALIDATION', 'INCIDENT_CREATED', 'INCIDENT_CLASSIFIED', 'TECHNICIAN_ASSIGNED', 'TECHNICIAN_ACCEPTED', 'TECHNICIAN_EN_ROUTE', 'TECHNICIAN_STARTED', 'INCIDENT_RESOLVED', 'INCIDENT_CANCELLED', 'OWNER_APPROVAL_REQUIRED', 'OWNER_APPROVED_EXPENSE', 'OWNER_REJECTED_EXPENSE', 'LOCK_ALERT_RECEIVED', 'PRICE_RECOMMENDATION_CREATED', 'PRICE_UPDATED_EXTERNAL', 'LEGAL_REGISTRATION_SUBMITTED', 'REVIEW_IMPORTED', 'REVIEW_RESPONSE_DRAFTED', 'REVIEW_RESPONSE_APPROVED', 'SLA_BREACH_WARNING', 'NOTIFICATION_SENT', 'NOTIFICATION_FAILED', 'WEBHOOK_RECEIVED', name='timeline_event_type'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='timeline_severity'), server_default='INFO', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_property_id_created_at', 'timeline_events', ['property_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_timeline_events_reservation_id_created_at', 'timeline_events', ['reservation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_timeline_events_tenant_id'), 'timeline_events', ['tenant_id'], unique=False)
    op.create_index('ix_timeline_events_tenant_id_event_type_created_at', 'timeline_events', ['tenant_id', 'event_type', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_events_tenant_id_event_type_created_at', table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_tenant_id'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_reservation_id_created_at', table_name='timeline_events')
    op.drop_index('ix_timeline_events_property_id_created_at', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_reservations_tenant_id_status', table_name='reservations')
    op.drop_index(op.f('ix_reservations_tenant_id'), table_name='reservations')
    op.drop_index('ix_reservations_property_id_check_out_date', table_name='reservations')
    op.drop_index('ix_reservations_property_id_check_in_date', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_property_state_transitions_tenant_id'), table_name='property_state_transitions')
    op.drop_index('ix_property_state_transitions_property_id_created_at', table_name='property_state_transitions')
    op.drop_table('property_state_transitions')
    op.drop_index('ix_users_tenant_id_status', table_name='users')
    op.drop_index('ix_users_tenant_id_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_configs')
    op.drop_index('ix_properties_tenant_id_pms_external_id', table_name='properties')
    op.drop_index('ix_properties_tenant_id_current_operational_state', table_name='properties')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_guests_tenant_id_email', table_name='guests')
    op.drop_index(op.f('ix_guests_tenant_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_table('tenants')
    for type_name in _ENUM_TYPE_NAMES:
        postgresql.ENUM(name=type_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
