"""auth sessions: user_sessions table for refresh token rotation state (R2.1-R2.3, design D5)

Adds the server-side state one refresh token needs: whether it has been used
(rotation), whether it has been revoked, and which lineage (`family_id`) it belongs
to so a reused token can take its whole family down. The primary key is the refresh
token's `jti`, so no token value is ever stored.

Revision ID: 8ff62a7cb50c
Revises: a1a72da30f8e
Create Date: 2026-07-30 07:00:32.709776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8ff62a7cb50c'
down_revision: Union[str, Sequence[str], None] = 'a1a72da30f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Postgres keeps a native enum type after its table is dropped, so downgrade has
# to remove it explicitly or a later upgrade fails with "type already exists".
# Same pattern as the two earlier migrations.
_ENUM_TYPE_NAMES = ('session_revoked_reason',)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Enum('LOGOUT', 'REUSE_DETECTED', name='session_revoked_reason'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['user_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_family_id', 'user_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_user_sessions_tenant_id_user_id', 'user_sessions', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_tenant_id_user_id', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_tenant_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_family_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    for type_name in _ENUM_TYPE_NAMES:
        postgresql.ENUM(name=type_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
