"""domain foundation financial

Revision ID: 96d526599bc1
Revises: e1eed2e039ee
Create Date: 2026-07-31 14:35:11.887833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d526599bc1'
down_revision: Union[str, Sequence[str], None] = 'e1eed2e039ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Autogenerate creates these Postgres ENUM types implicitly (as a side effect of
# the first CREATE TABLE that references each one) but never emits DROP TYPE for
# them on downgrade — dropped explicitly below to avoid leaving orphaned types
# (R5.2), same pattern as the baseline and the domain-foundation-ops migration.
# Leaving one behind makes the next upgrade fail with "type already exists".
_ENUM_TYPE_NAMES = [
    "price_recommendation_status",
    "owner_approval_related_type",
    "owner_approval_status",
    "review_channel",
    "review_sentiment",
    "review_status",
    "owner_statement_status",
    "expense_category",
    "notification_channel",
    "notification_status",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_provider_processed_received_at', 'webhook_events', ['provider', 'processed', 'received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_tenant_id'), 'webhook_events', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_id_actor_user_id_created_at', 'audit_logs', ['tenant_id', 'actor_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_tenant_id_entity_type_entity_id', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_contact', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'PUSH', 'IN_APP', 'CONSOLE', name='notification_channel'), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='notification_status'), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_type', sa.String(length=100), nullable=True),
    sa.Column('related_id', sa.Uuid(), nullable=True),
    sa.Column('sla_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_logs_related_type_related_id', 'notification_logs', ['related_type', 'related_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_tenant_id'), 'notification_logs', ['tenant_id'], unique=False)
    op.create_index('ix_notification_logs_tenant_id_status_sla_deadline_at', 'notification_logs', ['tenant_id', 'status', 'sla_deadline_at'], unique=False)
    op.create_table('owner_approvals',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('related_type', sa.Enum('INCIDENT', 'MAINTENANCE_COST', 'OTHER', name='owner_approval_related_type'), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='owner_approval_status'), server_default='PENDING', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('response_notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_approvals_tenant_id'), 'owner_approvals', ['tenant_id'], unique=False)
    op.create_table('owner_statements',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('ota_commissions', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('net_revenue', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('cleaning_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('laundry_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('amenities_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('maintenance_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('specialist_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('other_costs', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('net_owner_result', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SENT', name='owner_statement_status'), server_default='DRAFT', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'property_id', 'period_start', 'period_end', name='uq_owner_statements_tenant_property_period')
    )
    op.create_index(op.f('ix_owner_statements_tenant_id'), 'owner_statements', ['tenant_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_daily_change_pct', sa.Numeric(precision=5, scale=2), server_default='20.00', nullable=False),
    sa.Column('weekday_modifiers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('lead_time_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('occupancy_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('seasonality_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('event_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_tenant_id'), 'pricing_rules', ['tenant_id'], unique=False)
    op.create_table('price_recommendations',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_rule_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), server_default='1.00', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECOMMENDED', 'APPROVED', 'APPLIED_EXTERNAL', 'REJECTED', name='price_recommendation_status'), server_default='RECOMMENDED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_rule_id'], ['pricing_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'date', name='uq_price_recommendations_property_id_date')
    )
    op.create_index(op.f('ix_price_recommendations_tenant_id'), 'price_recommendations', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.Enum('AIRBNB', 'BOOKING', 'GOOGLE', 'MANUAL', 'OTHER', name='review_channel'), nullable=False),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='review_sentiment'), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('recurring_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DRAFTED', 'APPROVED', 'POSTED_MANUALLY', 'IGNORED', name='review_status'), server_default='NEW', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_tenant_id'), 'reviews', ['tenant_id'], unique=False)
    op.create_table('expenses',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('statement_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('CLEANING', 'LAUNDRY', 'AMENITIES', 'MAINTENANCE', 'SPECIALIST', 'PLATFORM_FEE', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('receipt_storage_key', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['statement_id'], ['owner_statements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_table('review_response_drafts',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('draft_content', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_response_drafts')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_reviews_tenant_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_price_recommendations_tenant_id'), table_name='price_recommendations')
    op.drop_table('price_recommendations')
    op.drop_index(op.f('ix_pricing_rules_tenant_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_owner_statements_tenant_id'), table_name='owner_statements')
    op.drop_table('owner_statements')
    op.drop_index(op.f('ix_owner_approvals_tenant_id'), table_name='owner_approvals')
    op.drop_table('owner_approvals')
    op.drop_index('ix_notification_logs_tenant_id_status_sla_deadline_at', table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_tenant_id'), table_name='notification_logs')
    op.drop_index('ix_notification_logs_related_type_related_id', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_audit_logs_tenant_id_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id_actor_user_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_webhook_events_tenant_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_processed_received_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    for type_name in _ENUM_TYPE_NAMES:
        postgresql.ENUM(name=type_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
