"""domain foundation ops

Revision ID: a1a72da30f8e
Revises: 4a5faad7796b
Create Date: 2026-07-17 09:13:34.294269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a72da30f8e'
down_revision: Union[str, Sequence[str], None] = '4a5faad7796b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Autogenerate creates these Postgres ENUM types implicitly (as a side
# effect of the first CREATE TABLE that references each one) but never
# emits DROP TYPE for them on downgrade — dropped explicitly below to avoid
# leaving orphaned types (R4.2), same pattern as the baseline migration.
_ENUM_TYPE_NAMES = [
    "cleaning_task_status",
    "cleaning_validation_status",
    "access_provider",
    "access_record_status",
    "access_created_mode",
    "conversation_channel",
    "conversation_status",
    "conversation_escalation_status",
    "incident_source",
    "incident_category",
    "incident_severity",
    "incident_status",
    "message_sender_type",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_checklist_templates',
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_checklist_templates_tenant_id'), 'cleaning_checklist_templates', ['tenant_id'], unique=False)
    op.create_table('access_records',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('GRINPASS', 'MANUAL', 'MOCK', 'EXTERNAL_MANAGED', name='access_provider'), server_default='MANUAL', nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CREATED_EXTERNAL', 'MANUAL_ADDED', 'DELIVERED', 'EXPIRED', 'REVOKED', name='access_record_status'), server_default='PENDING', nullable=False),
    sa.Column('code_masked', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_mode', sa.Enum('EXTERNAL_PMS_AUTOMATIC', 'MANUAL', 'MOCK', name='access_created_mode'), server_default='MANUAL', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_records_property_id_valid_from_valid_to', 'access_records', ['property_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_access_records_reservation_id', 'access_records', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_access_records_tenant_id'), 'access_records', ['tenant_id'], unique=False)
    op.create_table('cleaning_tasks',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('checklist_template_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_cleaner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED', name='cleaning_task_status'), server_default='CREATED', nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'PASSED', 'FAILED', 'WAIVED', name='cleaning_validation_status'), server_default='PENDING', nullable=False),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_cleaner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['cleaning_checklist_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cleaning_tasks_assigned_cleaner_id_status', 'cleaning_tasks', ['assigned_cleaner_id', 'status'], unique=False)
    op.create_index('ix_cleaning_tasks_property_id_status', 'cleaning_tasks', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_cleaning_tasks_tenant_id'), 'cleaning_tasks', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'AIRBNB_MSG', 'BOOKING_MSG', 'EMAIL', 'PHONE_TRANSCRIPT', 'MANUAL', name='conversation_channel'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'ESCALATED', 'CLOSED', name='conversation_status'), server_default='OPEN', nullable=False),
    sa.Column('language', sa.String(length=5), server_default='es', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('escalation_status', sa.Enum('NONE', 'PENDING_HUMAN', 'HUMAN_HANDLING', 'RESOLVED', name='conversation_escalation_status'), server_default='NONE', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_reservation_id', 'conversations', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_id_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_table('incidents',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reported_by_guest_token', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('GUEST', 'CLEANER', 'OWNER', 'SYSTEM', 'PMS', 'LOCK_ALERT', name='incident_source'), nullable=False),
    sa.Column('category', sa.Enum('ACCESS', 'LOCK', 'WIFI', 'ELECTRICITY', 'WATER', 'PLUMBING', 'HVAC', 'APPLIANCE', 'NOISE', 'CLEANING', 'DAMAGE', 'SAFETY', 'OTHER', name='incident_category'), server_default='OTHER', nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLASSIFIED', 'AWAITING_OWNER_APPROVAL', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'WAITING_EXTERNAL_PARTS', 'RESOLVED', 'CANCELLED', name='incident_status'), server_default='OPEN', nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('ai_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_technician_id', sa.Uuid(), nullable=True),
    sa.Column('owner_approval_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approved_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_property_id_status', 'incidents', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_index('ix_incidents_tenant_id_severity_status', 'incidents', ['tenant_id', 'severity', 'status'], unique=False)
    op.create_table('cleaning_checklist_completions',
    sa.Column('cleaning_task_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cleaning_task_id'], ['cleaning_tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_task_id', 'item_id', name='uq_cleaning_checklist_completions_cleaning_task_id_item_id')
    )
    op.create_table('cleaning_photos',
    sa.Column('cleaning_task_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('photo_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('ai_validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cleaning_task_id'], ['cleaning_tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cleaning_photos_cleaning_task_id', 'cleaning_photos', ['cleaning_task_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Enum('GUEST', 'OWNER', 'MANAGER', 'AI', 'SYSTEM', name='message_sender_type'), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_cleaning_photos_cleaning_task_id', table_name='cleaning_photos')
    op.drop_table('cleaning_photos')
    op.drop_table('cleaning_checklist_completions')
    op.drop_index('ix_incidents_tenant_id_severity_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index('ix_incidents_property_id_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_conversations_tenant_id_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index('ix_conversations_reservation_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_cleaning_tasks_tenant_id'), table_name='cleaning_tasks')
    op.drop_index('ix_cleaning_tasks_property_id_status', table_name='cleaning_tasks')
    op.drop_index('ix_cleaning_tasks_assigned_cleaner_id_status', table_name='cleaning_tasks')
    op.drop_table('cleaning_tasks')
    op.drop_index(op.f('ix_access_records_tenant_id'), table_name='access_records')
    op.drop_index('ix_access_records_reservation_id', table_name='access_records')
    op.drop_index('ix_access_records_property_id_valid_from_valid_to', table_name='access_records')
    op.drop_table('access_records')
    op.drop_index(op.f('ix_cleaning_checklist_templates_tenant_id'), table_name='cleaning_checklist_templates')
    op.drop_table('cleaning_checklist_templates')
    for type_name in _ENUM_TYPE_NAMES:
        postgresql.ENUM(name=type_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
