"""unique lower(email) per tenant: structural backstop for D19

`uq_users_tenant_id_email` is case-sensitive, so before this index `Jose@x.com` and
`jose@x.com` could coexist inside one tenant. The login lookup treats them as the
same address, gets two rows, and D16's "exactly one match" rule then leaves BOTH
accounts permanently unable to log in — a denial of access anyone able to create
users could trigger against a known email. `normalize_email` lowercases on every
write; this index makes that invariant enforced rather than merely intended.

Additive only: creates an index, alters no column.

Revision ID: e1eed2e039ee
Revises: 8ff62a7cb50c
Create Date: 2026-07-30 07:22:22.460047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1eed2e039ee'
down_revision: Union[str, Sequence[str], None] = '8ff62a7cb50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_tenant_id_lower_email', 'users', ['tenant_id', sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_tenant_id_lower_email', table_name='users')
    # ### end Alembic commands ###
