import enum


class TimelineActorType(str, enum.Enum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    GUEST = "GUEST"
    SCHEDULER = "SCHEDULER"
    WEBHOOK = "WEBHOOK"
    AI = "AI"


class TimelineSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class TimelineEventType(str, enum.Enum):
    RESERVATION_IMPORTED = "RESERVATION_IMPORTED"
    RESERVATION_CREATED_MANUAL = "RESERVATION_CREATED_MANUAL"
    RESERVATION_UPDATED = "RESERVATION_UPDATED"
    RESERVATION_CANCELLED = "RESERVATION_CANCELLED"
    CHECKIN_WINDOW_OPENED = "CHECKIN_WINDOW_OPENED"
    CHECKOUT_WINDOW_REACHED = "CHECKOUT_WINDOW_REACHED"
    PROPERTY_STATE_CHANGED = "PROPERTY_STATE_CHANGED"
    ACCESS_CODE_PENDING = "ACCESS_CODE_PENDING"
    ACCESS_CODE_CREATED_EXTERNAL = "ACCESS_CODE_CREATED_EXTERNAL"
    ACCESS_CODE_MANUAL_ADDED = "ACCESS_CODE_MANUAL_ADDED"
    ACCESS_CODE_DELIVERED = "ACCESS_CODE_DELIVERED"
    GUEST_MESSAGE_RECEIVED = "GUEST_MESSAGE_RECEIVED"
    AI_RESPONSE_SENT = "AI_RESPONSE_SENT"
    AI_ESCALATED_TO_HUMAN = "AI_ESCALATED_TO_HUMAN"
    HUMAN_RESPONSE_SENT = "HUMAN_RESPONSE_SENT"
    CLEANING_TASK_CREATED = "CLEANING_TASK_CREATED"
    CLEANER_ASSIGNED = "CLEANER_ASSIGNED"
    CLEANER_ACCEPTED = "CLEANER_ACCEPTED"
    CLEANER_REJECTED = "CLEANER_REJECTED"
    CLEANING_STARTED = "CLEANING_STARTED"
    CLEANING_PHOTO_UPLOADED = "CLEANING_PHOTO_UPLOADED"
    CLEANING_COMPLETED = "CLEANING_COMPLETED"
    CLEANING_FAILED_VALIDATION = "CLEANING_FAILED_VALIDATION"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_CLASSIFIED = "INCIDENT_CLASSIFIED"
    TECHNICIAN_ASSIGNED = "TECHNICIAN_ASSIGNED"
    TECHNICIAN_ACCEPTED = "TECHNICIAN_ACCEPTED"
    # The technician refused the job and it went back to the manager
    # (`tech-cycle-completion` R1.9). None of the values above says it: `TECHNICIAN_ACCEPTED`
    # is its opposite, `INCIDENT_CANCELLED` is the manager closing the incident for good, and
    # `CLEANER_REJECTED` is the other trade. Added outside PRD §7.8's list with the precedent
    # of `GUEST_CHECKIN_COMPLETED`, which `guest-portal-api` added for the same reason.
    TECHNICIAN_REJECTED = "TECHNICIAN_REJECTED"
    TECHNICIAN_EN_ROUTE = "TECHNICIAN_EN_ROUTE"
    TECHNICIAN_STARTED = "TECHNICIAN_STARTED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_CANCELLED = "INCIDENT_CANCELLED"
    OWNER_APPROVAL_REQUIRED = "OWNER_APPROVAL_REQUIRED"
    OWNER_APPROVED_EXPENSE = "OWNER_APPROVED_EXPENSE"
    OWNER_REJECTED_EXPENSE = "OWNER_REJECTED_EXPENSE"
    LOCK_ALERT_RECEIVED = "LOCK_ALERT_RECEIVED"
    PRICE_RECOMMENDATION_CREATED = "PRICE_RECOMMENDATION_CREATED"
    PRICE_UPDATED_EXTERNAL = "PRICE_UPDATED_EXTERNAL"
    LEGAL_REGISTRATION_SUBMITTED = "LEGAL_REGISTRATION_SUBMITTED"
    REVIEW_IMPORTED = "REVIEW_IMPORTED"
    REVIEW_RESPONSE_DRAFTED = "REVIEW_RESPONSE_DRAFTED"
    REVIEW_RESPONSE_APPROVED = "REVIEW_RESPONSE_APPROVED"
    SLA_BREACH_WARNING = "SLA_BREACH_WARNING"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    # The guest completed their own check-in through the portal (`guest-portal-api` R6.3,
    # design D12). None of the values above says it: `CHECKIN_WINDOW_OPENED` is the clock,
    # not the guest, and reusing `LEGAL_REGISTRATION_SUBMITTED` would be a permanent claim
    # — the timeline is append-only — that a filing with the police happened when it did
    # not. Written only when the legal status actually transitions (D13), so a resent form
    # does not add a second row to an immutable table.
    GUEST_CHECKIN_COMPLETED = "GUEST_CHECKIN_COMPLETED"
