import enum


class PropertyOperationalState(str, enum.Enum):
    VACANT_READY = "VACANT_READY"
    AWAITING_CHECKIN = "AWAITING_CHECKIN"
    OCCUPIED_ESTIMATED = "OCCUPIED_ESTIMATED"
    AWAITING_CLEANING = "AWAITING_CLEANING"
    CLEANING_SCHEDULED = "CLEANING_SCHEDULED"
    CLEANING_IN_PROGRESS = "CLEANING_IN_PROGRESS"
    READY_FOR_NEXT_GUEST = "READY_FOR_NEXT_GUEST"
    MAINTENANCE_REQUIRED = "MAINTENANCE_REQUIRED"
    CRITICAL_INCIDENT = "CRITICAL_INCIDENT"
    BLOCKED_BY_OWNER = "BLOCKED_BY_OWNER"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"


class PropertyStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class StateTransitionTriggeredBy(str, enum.Enum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    SCHEDULER = "SCHEDULER"
    WEBHOOK = "WEBHOOK"
