import enum


class PropertyStateTrigger(str, enum.Enum):
    CHECKIN_WINDOW_OPENED = "CHECKIN_WINDOW_OPENED"
    CHECKIN_TIME_REACHED = "CHECKIN_TIME_REACHED"
    CHECKOUT_TIME_REACHED = "CHECKOUT_TIME_REACHED"
    RESERVATION_CANCELLED_BEFORE_CHECKIN = "RESERVATION_CANCELLED_BEFORE_CHECKIN"
    CLEANER_ASSIGNED = "CLEANER_ASSIGNED"
    CLEANER_REJECTED = "CLEANER_REJECTED"
    CLEANING_STARTED = "CLEANING_STARTED"
    CLEANING_COMPLETED = "CLEANING_COMPLETED"
    CLEANING_CANCELLED = "CLEANING_CANCELLED"
    INCIDENT_HIGH = "INCIDENT_HIGH"
    INCIDENT_CRITICAL = "INCIDENT_CRITICAL"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    OWNER_BLOCKED = "OWNER_BLOCKED"
    PROPERTY_MARKED_OUT_OF_SERVICE = "PROPERTY_MARKED_OUT_OF_SERVICE"
    PROPERTY_REACTIVATED = "PROPERTY_REACTIVATED"
    OWNER_MANAGER_UNBLOCKED = "OWNER_MANAGER_UNBLOCKED"
