"""User-administration endpoints (PRD §23, R1-R4, R7).

Thin by contract: map Pydantic → use case → Pydantic. Every route declares its permission with
`require(...)`, which is what `tests/test_route_authorization.py` walks — a route added here
without one fails the suite.

Authorisation is decided by that dependency, which runs BEFORE the endpoint body and therefore
before any lookup: a role without permission gets the same `403` for a real id and for an
invented one (R7.3).
"""

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, Query, Response, status

from app.core.openapi import AUTHENTICATED_RESPONSES
from app.auth.api.dependencies import AuthenticatedRequest, get_client_ip, now_utc, require
from app.auth.api.user_schemas import (
    MAX_PAGE,
    MAX_PER_PAGE,
    CreatedUserResponse,
    CreateUserRequest,
    UpdateUserRequest,
    UserPageResponse,
    UserResponse,
)
from app.auth.api.user_dependencies import (
    get_create_user_use_case,
    get_deactivate_user_use_case,
    get_list_users_use_case,
    get_reset_password_use_case,
    get_update_user_use_case,
    get_user_use_case,
)
from app.auth.application.user_admin import (
    CreateUserCommand,
    CreateUserUseCase,
    DeactivateUserUseCase,
    GetUserUseCase,
    ListUsersUseCase,
    ResetUserPasswordUseCase,
    UpdateUserUseCase,
)
from app.auth.domain.enums import UserRole, UserStatus
from app.auth.domain.policy import Permission
from app.auth.domain.repositories import UserFilters

router = APIRouter(
    prefix="/users", tags=["users"], responses=AUTHENTICATED_RESPONSES
)

ReadDep = Annotated[AuthenticatedRequest, Depends(require(Permission.READ_USERS))]
ManageDep = Annotated[AuthenticatedRequest, Depends(require(Permission.MANAGE_USERS))]
ClientIpDep = Annotated[str, Depends(get_client_ip)]

# The two responses that carry a one-time secret must not be stored by any intermediary
# (design D10). Applied to the response object rather than globally, so it is visible at the
# two endpoints it protects.
NO_STORE = {"Cache-Control": "no-store"}


@router.get(
    "",
    response_model=UserPageResponse,
    summary="List the tenant's users",
    description=(
        "Paginated with `page`/`per_page` (PRD §23) and filterable by role and status, which "
        "combine with AND. Ordered by name with the id as a tiebreaker, so paginating never "
        "repeats or skips a row. Never includes any password material."
    ),
)
async def list_users(
    authenticated: ReadDep,
    use_case: Annotated[ListUsersUseCase, Depends(get_list_users_use_case)],
    page: Annotated[int, Query(ge=1, le=MAX_PAGE)] = 1,
    per_page: Annotated[int, Query(ge=1, le=MAX_PER_PAGE)] = 20,
    role: UserRole | None = None,
    status_filter: Annotated[UserStatus | None, Query(alias="status")] = None,
) -> UserPageResponse:
    result = await use_case.execute(
        tenant_id=authenticated.context.tenant_id,
        filters=UserFilters(role=role, status=status_filter),
        page=page,
        per_page=per_page,
    )
    return UserPageResponse.build(
        result.items, total=result.total, page=page, per_page=per_page
    )


@router.post(
    "",
    response_model=CreatedUserResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a user and issue its temporary password",
    description=(
        "The password is generated by the system and returned **exactly once**, in this "
        "response; it is never stored in cleartext, logged, or written to the audit trail. "
        "Answers `409` if the address is already in use anywhere in the installation "
        "(ADR 0005), and `422` for `SUPER_ADMIN`, whose powers are global rather than "
        "tenant-scoped."
    ),
)
async def create_user(
    body: CreateUserRequest,
    authenticated: ManageDep,
    client_ip: ClientIpDep,
    use_case: Annotated[CreateUserUseCase, Depends(get_create_user_use_case)],
    response: Response,
) -> CreatedUserResponse:
    created = await use_case.execute(
        tenant_id=authenticated.context.tenant_id,
        actor_user_id=authenticated.context.user_id,
        actor_ip=client_ip,
        command=CreateUserCommand(
            name=body.name,
            email=str(body.email),
            role=body.role,
            phone=body.phone,
            preferred_language=body.preferred_language,
        ),
        now=now_utc(),
    )
    response.headers.update(NO_STORE)
    return CreatedUserResponse.build(created.user, created.temporary_password)


@router.get(
    "/{user_id}",
    response_model=UserResponse,
    summary="One user of the tenant",
    description=(
        "A user of another tenant answers `404`, indistinguishable from one that does not "
        "exist. Includes users that are not ACTIVE, so a suspended account can be found in "
        "order to reactivate it."
    ),
)
async def get_user(
    user_id: uuid.UUID,
    authenticated: ReadDep,
    use_case: Annotated[GetUserUseCase, Depends(get_user_use_case)],
) -> UserResponse:
    user = await use_case.execute(
        tenant_id=authenticated.context.tenant_id, user_id=user_id
    )
    return UserResponse.from_domain(user)


@router.patch(
    "/{user_id}",
    response_model=UserResponse,
    summary="Update a user partially",
    description=(
        "Only the fields present in the body are applied, and only the columns that really "
        "changed are written. A body that changes nothing writes neither a row nor an audit "
        "entry. Answers `422` when an actor targets their own role or status, and when the "
        "change would leave the tenant without an active owner. Disabling a user revokes "
        "every one of its refresh sessions."
    ),
)
async def update_user(
    user_id: uuid.UUID,
    body: UpdateUserRequest,
    authenticated: ManageDep,
    client_ip: ClientIpDep,
    use_case: Annotated[UpdateUserUseCase, Depends(get_update_user_use_case)],
) -> UserResponse:
    user = await use_case.execute(
        tenant_id=authenticated.context.tenant_id,
        actor_user_id=authenticated.context.user_id,
        actor_ip=client_ip,
        user_id=user_id,
        changes=body.changes(),
        now=now_utc(),
    )
    return UserResponse.from_domain(user)


@router.delete(
    "/{user_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Deactivate a user",
    description=(
        "Logical deactivation, not physical deletion: the row stays and its status becomes "
        "`INACTIVE`, because the audit trail and the timeline point at it. Idempotent — "
        "deactivating an already inactive user answers `204` and adds no second audit entry. "
        "Refuses self-deactivation and the removal of the last active owner."
    ),
)
async def deactivate_user(
    user_id: uuid.UUID,
    authenticated: ManageDep,
    client_ip: ClientIpDep,
    use_case: Annotated[DeactivateUserUseCase, Depends(get_deactivate_user_use_case)],
) -> Response:
    await use_case.execute(
        tenant_id=authenticated.context.tenant_id,
        actor_user_id=authenticated.context.user_id,
        actor_ip=client_ip,
        user_id=user_id,
        now=now_utc(),
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.post(
    "/{user_id}/reset-password",
    response_model=CreatedUserResponse,
    summary="Issue a new temporary password for a user",
    description=(
        "Not part of the endpoint list of PRD §23: a deliberate addition, because "
        "`auth-account-recovery` is optional in PRD §24 and depends on the notification "
        "adapter, so without this the MVP has no recovery path at all. Replaces the stored "
        "hash, returns the new password exactly once and revokes every refresh session of the "
        "affected user — a reset that left them alive would not recover the account, it would "
        "just add one more credential to it."
    ),
)
async def reset_user_password(
    user_id: uuid.UUID,
    authenticated: ManageDep,
    client_ip: ClientIpDep,
    use_case: Annotated[ResetUserPasswordUseCase, Depends(get_reset_password_use_case)],
    response: Response,
) -> CreatedUserResponse:
    result = await use_case.execute(
        tenant_id=authenticated.context.tenant_id,
        actor_user_id=authenticated.context.user_id,
        actor_ip=client_ip,
        user_id=user_id,
        now=now_utc(),
    )
    response.headers.update(NO_STORE)
    return CreatedUserResponse.build(result.user, result.temporary_password)
